### ISSUE TITLE
Couldn’t find the namespace in Test class

### ISSUE THREAD

**Issue by heverton-sarah-playkids** [BoundfoxStudios/fluentassertions-unity#2]
I tried accessing the namespace inside a Test class (Play Mode and Editor Mode) but Unity is not finding? What is the correct namespace after adding the assembly reference into Test assembly definition?

**Comment by ManuelRauber** [comment]
Hi, 

it should be BoundfoxStudios.FluentAssertions. 

Did you install via open upm?

**Comment by gtoto007** [comment]
I've same issue. I used Unity 2020.1.14f and I've installed the package with git mode. 
<img width="1676" alt="Schermata 2020-12-29 alle 23 40 32" src="https://user-images.githubusercontent.com/6715157/103318622-4cf56100-4a2f-11eb-9381-112cd2032717.png">

**Comment by ManuelRauber** [comment]
@gtoto007 Yes, you're right. Something went wrong with the current release. I check that.

**Comment by ManuelRauber** [comment]
@heverton-sarah-playkids @gtoto007 Can you please update to the latest package version and verify, you have installed **5.10.3-r3**. Then, add `BoundfoxStudios.FluentAssertions` to your test asmdef. After that, a simple import of `using FluentAssertions;` should work.

Please re-open the issue, if the the issue still persists.
