### ISSUE TITLE
Doesn't compile when importing via OpenUPM

### ISSUE THREAD

**Issue by razenpok** [BoundfoxStudios/fluentassertions-unity#4]
I'm using Unity 2019.4.16f1 with `Api Compatibility Level` = `.NET Standard 2.0`

![image](https://user-images.githubusercontent.com/8434406/115868402-0f38a000-a445-11eb-8637-8ce87b953861.png)

**Comment by ManuelRauber** [comment]
Hi!

Thanks for the report. I will investigate the issue.

**Comment by ManuelRauber** [comment]
@Razenpok 
Please add the scripting symbol `NETSTANDARD2_0` to your Scripting Symbols (Edit -> Project Settings -> Player -> Other Settings -> Scripting Define Symbols).

It looks like the older Unity version did not define it themselves when using the .NET Standard backend.

I will update the README with this information.

Thanks for spotting the bug!

**Comment by razenpok** [comment]
Woo, thanks!
