### ISSUE TITLE
Console errors after importing package

### ISSUE THREAD

**Issue by CLV9** [BoundfoxStudios/fluentassertions-unity#5]
Hello. After imporing package i have some errors in console.
My player settings:
![Player Settings](https://sun9-52.userapi.com/impg/DGJWOmedAlRcgAQgFKH0y5j1XSE2-0BzTRZGJg/3TNNK35Mmcc.jpg?size=1454x152&quality=96&sign=cbe080c3573ff436be157611ea3116c7&type=album)
Errors: 
![Console Erros](https://sun9-70.userapi.com/impg/f_rebfurv1YSi1rYMh6cmiJGSffJu1ESUgbqYw/nccaJeH5sm8.jpg?size=996x266&quality=96&sign=929864cb786e2f7aa6258b87a36663d6&type=album)
Example:
`Library\PackageCache\com.boundfoxstudios.fluentassertions@58a427c777\Editor\FluentAssertions\AssertionExtensions.cs(102,10): error CS0246: The type or namespace name 'MustUseReturnValueAttribute' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by ManuelRauber** [comment]
@CLV9 Which Unity Version are you using?

**Comment by ManuelRauber** [comment]
Closed due to inactivity.
